# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Businesses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('street', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=45)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.IntegerField()),
                ('google_place_id', models.CharField(max_length=100, null=True)),
                ('yelp_id', models.CharField(max_length=45, null=True)),
                ('yelp_rating', models.FloatField(max_length=4, null=True)),
                ('yelp_price_level', models.CharField(max_length=5, null=True)),
                ('yelp_no_of_reviews', models.IntegerField(null=True)),
                ('latitude', models.FloatField(max_length=25, null=True)),
                ('longitude', models.FloatField(max_length=25, null=True)),
                ('phone', models.CharField(max_length=14, null=True)),
            ],
        ),
    ]
